from django.urls import path

from .views import (
    client_interaction_create,
    client_create,
    client_delete,
    client_details,
    client_update,
    clients_list,
    contact_create,
    contact_delete,
    contact_update,
    contacts_list,
    inventory_dashboard,
    inventory_receipt_create,
    inventory_transaction_create,
    material_create,
    materials_list,
    order_create,
    order_delete,
    order_materials,
    order_update,
    orders_list,
    product_create,
    product_delete,
    product_details,
    product_update,
    products_list,
    task_create,
    task_delete,
    task_status_update,
    task_update,
    tasks_kanban,
    tasks_list,
)


urlpatterns = [
    path("crm/clients/", clients_list, name="crm_clients"),
    path("crm/clients/new/", client_create, name="crm_client_create"),
    path("crm/clients/<int:client_id>/", client_details, name="client_details"),
    path("crm/clients/<int:client_id>/interactions/new/", client_interaction_create, name="crm_client_interaction_create"),
    path("crm/clients/<int:client_id>/edit/", client_update, name="crm_client_update"),
    path("crm/clients/<int:client_id>/delete/", client_delete, name="crm_client_delete"),
    path("crm/contacts/", contacts_list, name="crm_contacts"),
    path("crm/contacts/new/", contact_create, name="crm_contact_create"),
    path("crm/contacts/<int:contact_id>/edit/", contact_update, name="crm_contact_update"),
    path("crm/contacts/<int:contact_id>/delete/", contact_delete, name="crm_contact_delete"),
    path("crm/orders/", orders_list, name="crm_orders"),
    path("crm/orders/new/", order_create, name="crm_order_create"),
    path("crm/orders/<int:order_id>/materials/", order_materials, name="crm_order_materials"),
    path("crm/orders/<int:order_id>/edit/", order_update, name="crm_order_update"),
    path("crm/orders/<int:order_id>/delete/", order_delete, name="crm_order_delete"),
    path("crm/tasks/", tasks_list, name="crm_tasks"),
    path("crm/tasks/kanban/", tasks_kanban, name="crm_tasks_kanban"),
    path("crm/tasks/new/", task_create, name="crm_task_create"),
    path("crm/tasks/<int:task_id>/status/", task_status_update, name="crm_task_status_update"),
    path("crm/tasks/<int:task_id>/edit/", task_update, name="crm_task_update"),
    path("crm/tasks/<int:task_id>/delete/", task_delete, name="crm_task_delete"),
    path("crm/products/", products_list, name="crm_products"),
    path("crm/materials/", materials_list, name="crm_materials"),
    path("crm/products/<int:product_id>/", product_details, name="crm_product_details"),
    path("crm/materials/new/", material_create, name="crm_material_create"),
    path("crm/products/new/", product_create, name="crm_product_create"),
    path("crm/products/<int:product_id>/edit/", product_update, name="crm_product_update"),
    path("crm/products/<int:product_id>/delete/", product_delete, name="crm_product_delete"),
    path("crm/inventory/", inventory_dashboard, name="crm_inventory"),
    path("crm/inventory/receipts/new/", inventory_receipt_create, name="crm_inventory_receipt_create"),
    path("crm/inventory/transactions/new/", inventory_transaction_create, name="crm_inventory_transaction_create"),
]
