# Generated by Django 5.2.8 on 2025-12-25 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ім’я / назва клієнта')),
                ('client_type', models.CharField(choices=[('fop', 'ФОП'), ('tov', 'ТОВ'), ('individual', 'Фізособа')], default='individual', max_length=16, verbose_name='Тип клієнта')),
                ('tax_code', models.CharField(blank=True, help_text='Обов’язково для ФОП/ТОВ.', max_length=16, verbose_name='Код ЄДРПОУ / РНОКПП')),
                ('phones', models.CharField(blank=True, help_text='Кілька через кому', max_length=255, verbose_name='Телефони')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('source', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('prom', 'Prom.ua'), ('olx', 'OLX'), ('phone', 'Телефон'), ('recommendation', 'Рекомендація'), ('word_of_mouth', 'Сарафанне радіо'), ('other', 'Інше')], default='other', max_length=32, verbose_name='Джерело клієнта')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Клієнт',
                'verbose_name_plural': 'Клієнти',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва продукту')),
                ('sku', models.CharField(blank=True, help_text='Необов’язково, але бажано для уніфікації', max_length=100, null=True, unique=True, verbose_name='Артикул / код')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Базова ціна')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукти',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Посада')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('source', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('prom', 'Prom.ua'), ('olx', 'OLX'), ('phone', 'Телефон'), ('recommendation', 'Рекомендація'), ('word_of_mouth', 'Сарафанне радіо'), ('other', 'Інше')], default='other', max_length=32, verbose_name='Джерело контакту')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='crm.client', verbose_name='Клієнт')),
                ('tags', models.ManyToManyField(blank=True, related_name='contacts', to='crm.tag')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакти',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новий'), ('in_progress', 'В роботі'), ('shipped', 'Відправлений'), ('completed', 'Завершений'), ('canceled', 'Відмінений')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Дедлайн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('comment', models.TextField(blank=True, verbose_name='Додаткові нотатки')),
                ('shipping_address', models.CharField(blank=True, max_length=500, verbose_name='Адреса відправки')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='№ ТТН')),
                ('recipient', models.CharField(blank=True, max_length=255, verbose_name='Отримувач')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сума оплати')),
                ('payment_type', models.CharField(blank=True, choices=[('cod', 'Післяплата'), ('prepay', 'Передоплата'), ('partial_prepay', 'Часткова передоплата'), ('cashless', 'Безготівка'), ('free', 'Гарантія / безкоштовно')], max_length=20, null=True, verbose_name='Тип оплати')),
                ('delivery_method', models.CharField(blank=True, choices=[('nova_poshta', 'Нова Пошта'), ('ukrposhta', 'Укрпошта'), ('courier', 'Кур’єр'), ('pickup', 'Самовивіз'), ('other', 'Інше')], max_length=20, null=True, verbose_name='Метод доставки')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='crm.contact', verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна за одиницю')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Коментар')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.order', verbose_name='Замовлення')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='crm.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Позиція замовлення',
                'verbose_name_plural': 'Позиції замовлення',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='clients', to='crm.tag'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва задачі')),
                ('date', models.DateField(db_index=True, verbose_name='Дата задачі')),
                ('status', models.BooleanField(default=False, help_text='Позначає, чи задача виконана', verbose_name='Виконано')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned_by', to=settings.AUTH_USER_MODEL, verbose_name='Ким створена')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Кому призначена')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.contact', verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачі',
                'ordering': ['date', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['client', 'full_name'], name='crm_contact_client__6946e1_idx'),
        ),
    ]
