# Generated by Django 5.2.8 on 2025-12-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_terms',
            field=models.CharField(blank=True, help_text='Напр.: 50% передоплата / оплата при отриманні / оплата 3 дні після відвантаження', max_length=255, verbose_name='Умови оплати'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон отримувача'),
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(blank=True, editable=False, help_text='Формується автоматично з товарів у позиціях замовлення.', max_length=500, verbose_name='Назва замовлення (авто)'),
        ),
    ]
