# Generated by Django 5.2.8 on 2025-12-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_order_payment_terms_order_recipient_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='olx_url',
            field=models.URLField(blank=True, verbose_name='OLX'),
        ),
        migrations.AddField(
            model_name='product',
            name='photos_url',
            field=models.URLField(blank=True, help_text='Google Drive / Dropbox / CDN', verbose_name='Посилання на фото'),
        ),
        migrations.AddField(
            model_name='product',
            name='production_norms_url',
            field=models.URLField(blank=True, verbose_name='Норми виробництва (Google Drive)'),
        ),
        migrations.AddField(
            model_name='product',
            name='prom_url',
            field=models.URLField(blank=True, verbose_name='Prom.ua'),
        ),
        migrations.AddField(
            model_name='product',
            name='rozetka_url',
            field=models.URLField(blank=True, verbose_name='Rozetka'),
        ),
        migrations.AddField(
            model_name='product',
            name='site_url',
            field=models.URLField(blank=True, verbose_name='Сайт'),
        ),
        migrations.AddField(
            model_name='product',
            name='technical_description',
            field=models.TextField(blank=True, verbose_name='Технічний опис'),
        ),
    ]
