# Generated by Django 5.2.8 on 2026-03-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_task_workflow_and_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('low', 'Низький'), ('normal', 'Нормальний'), ('high', 'Високий'), ('urgent', 'Терміновий')], db_index=True, default='normal', max_length=16, verbose_name='Пріоритет'),
        ),
    ]
