# Generated by Django 5.2.8 on 2026-03-22 11:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_client_interactions(apps, schema_editor):
    ClientInteraction = apps.get_model("crm", "ClientInteraction")
    Contact = apps.get_model("crm", "Contact")
    Order = apps.get_model("crm", "Order")
    Task = apps.get_model("crm", "Task")

    interactions = []
    for contact in Contact.objects.select_related("client"):
        interactions.append(
            ClientInteraction(
                client_id=contact.client_id,
                contact_id=contact.id,
                event_type="contact",
                source="system",
                title=f"Створено контакт: {contact.full_name}",
                description="",
                event_at=contact.created_at,
                created_at=contact.created_at,
                payload={"action": "backfill_contact_created"},
            )
        )
    for order in Order.objects.select_related("contact", "manager"):
        interactions.append(
            ClientInteraction(
                client_id=order.contact.client_id,
                contact_id=order.contact_id,
                order_id=order.id,
                created_by_id=order.manager_id,
                event_type="order",
                source="system",
                title=f"Створено замовлення: {order.title or f'Замовлення #{order.id}'}",
                description="",
                event_at=order.created_at,
                created_at=order.created_at,
                payload={"action": "backfill_order_created"},
            )
        )
    for task in Task.objects.select_related("client", "contact", "order", "assigned_by"):
        interactions.append(
            ClientInteraction(
                client_id=task.client_id,
                contact_id=task.contact_id,
                order_id=task.order_id,
                task_id=task.id,
                created_by_id=task.assigned_by_id,
                event_type="task",
                source="system",
                title=f"Створено задачу: {task.title}",
                description="",
                event_at=task.created_at,
                created_at=task.created_at,
                payload={"action": "backfill_task_created"},
            )
        )
    if interactions:
        ClientInteraction.objects.bulk_create(interactions, batch_size=500)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_order_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('note', 'Нотатка'), ('call', 'Дзвінок'), ('message', 'Повідомлення'), ('comment', 'Коментар'), ('contact', 'Контакт'), ('order', 'Замовлення'), ('task', 'Задача'), ('production', 'Виробництво'), ('system', 'Службова подія')], db_index=True, default='system', max_length=20, verbose_name='Тип події')),
                ('source', models.CharField(choices=[('manual', 'Ручне внесення'), ('auto', 'Автоматично'), ('system', 'Система')], db_index=True, default='system', max_length=16, verbose_name='Джерело')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('event_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата події')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Додаткові дані')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.client', verbose_name='Клієнт')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='crm.contact', verbose_name='Контакт')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_interactions', to=settings.AUTH_USER_MODEL, verbose_name='Хто зафіксував')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='crm.order', verbose_name='Замовлення')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='crm.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Історія взаємодії',
                'verbose_name_plural': 'Історія взаємодій',
                'ordering': ['-event_at', '-id'],
                'indexes': [models.Index(fields=['client', 'event_at'], name='crm_clienti_client__9f4f56_idx'), models.Index(fields=['event_type', 'event_at'], name='crm_clienti_event_t_dac300_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductProductionNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(choices=[('intake', 'Приймання'), ('procurement', 'Закупка матеріалів'), ('execution', 'Виконання'), ('painting', 'Фарбування'), ('ready_to_ship', 'Готово до відправки')], db_index=True, max_length=32, verbose_name='Тип етапу')),
                ('time_value', models.DecimalField(decimal_places=2, help_text='Тривалість етапу для однієї одиниці продукції.', max_digits=8, verbose_name='Норма часу')),
                ('time_unit', models.CharField(choices=[('minutes', 'Хвилини'), ('hours', 'Години')], default='hours', max_length=16, verbose_name='Одиниця норми часу')),
                ('material_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Норма матеріалу')),
                ('material_unit', models.CharField(choices=[('piece', 'шт'), ('square_meter', 'м²'), ('kilogram', 'кг'), ('meter', 'м'), ('liter', 'л'), ('other', 'Інше')], default='piece', max_length=24, verbose_name='Одиниця норми матеріалу')),
                ('version', models.CharField(blank=True, default='v1', max_length=50, verbose_name='Версія')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Коментар')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний норматив')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_norms', to='crm.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Норматив виробництва',
                'verbose_name_plural': 'Нормативи виробництва',
                'ordering': ['product__name', 'stage_type', '-is_active', '-updated_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('product', 'stage_type', 'version'), name='crm_unique_product_stage_norm_version')],
            },
        ),
        migrations.RunPython(backfill_client_interactions, noop_reverse),
    ]
