# Generated by Django 5.2.8 on 2026-03-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_clientinteraction_productproductionnorm'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Низький'), ('normal', 'Нормальний'), ('high', 'Високий'), ('urgent', 'Терміновий')], db_index=True, default='normal', max_length=16, verbose_name='Пріоритет'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Дедлайн'),
        ),
    ]
