# Generated by Django 5.2.8 on 2026-03-26 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_client_email_alter_contact_email'),
        ('manufacture', '0005_alter_productionslot_planning_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Назва складу')),
                ('type', models.CharField(choices=[('raw', 'Сировина'), ('wip', 'Незавершене виробництво'), ('finished', 'Готова продукція')], db_index=True, default='raw', max_length=16, verbose_name='Тип складу')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склади',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='consumed_materials',
            field=models.JSONField(blank=True, default=list, verbose_name='Списані матеріали'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='required_materials',
            field=models.JSONField(blank=True, default=list, verbose_name='Потрібні матеріали'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='reserved_materials',
            field=models.JSONField(blank=True, default=list, verbose_name='Зарезервовані матеріали'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_material',
            field=models.BooleanField(default=False, verbose_name='Є матеріалом'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock_level',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Мінімальний залишок'),
        ),
        migrations.AddField(
            model_name='product',
            name='track_inventory',
            field=models.BooleanField(default=True, verbose_name='Вести складський облік'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, default='шт', max_length=32, verbose_name='Одиниця виміру'),
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('in', 'Прихід'), ('out', 'Списання'), ('move', 'Переміщення'), ('reserve', 'Резерв'), ('release', 'Зняття резерву')], db_index=True, max_length=16, verbose_name='Тип операції')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Кількість')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Створено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Ким створено')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='crm.order', verbose_name='Замовлення')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='crm.orderitem', verbose_name='Позиція замовлення')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='crm.product', verbose_name='Продукт')),
                ('production_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='manufacture.productionstage', verbose_name='Етап виробництва')),
                ('warehouse_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='crm.warehouse', verbose_name='Склад джерело')),
                ('warehouse_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='crm.warehouse', verbose_name='Склад призначення')),
            ],
            options={
                'verbose_name': 'Складська операція',
                'verbose_name_plural': 'Складські операції',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Кількість')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_bom', to='crm.product', verbose_name='Матеріал')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='crm.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'BOM продукту',
                'verbose_name_plural': 'BOM продуктів',
                'ordering': ['product__name', 'material__name'],
                'constraints': [models.UniqueConstraint(fields=('product', 'material'), name='crm_unique_product_bom_material')],
            },
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Кількість')),
                ('reserved_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Зарезервовано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balances', to='crm.product', verbose_name='Продукт')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balances', to='crm.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Залишок на складі',
                'verbose_name_plural': 'Залишки на складах',
                'ordering': ['product__name', 'warehouse__name'],
                'constraints': [models.UniqueConstraint(fields=('product', 'warehouse'), name='crm_unique_inventory_balance_product_warehouse')],
            },
        ),
    ]
