# Generated by Django 5.2.8 on 2026-03-26 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_warehouse_orderitem_consumed_materials_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbom',
            options={'ordering': ['product__name', 'material__name'], 'verbose_name': 'Склад продукту', 'verbose_name_plural': 'Склад продуктів'},
        ),
    ]
