# Generated by Django 5.2.8 on 2026-03-26 23:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_productbom_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, max_length=255, verbose_name='Постачальник')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Номер накладної')),
                ('document_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Дата накладної')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Створено')),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Проведено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_receipts_created', to=settings.AUTH_USER_MODEL, verbose_name='Ким створено')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_receipts_posted', to=settings.AUTH_USER_MODEL, verbose_name='Ким проведено')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_receipts', to='crm.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Прибуткова накладна',
                'verbose_name_plural': 'Прибуткові накладні',
                'ordering': ['-document_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='crm.inventoryreceipt', verbose_name='Прибуткова накладна'),
        ),
        migrations.CreateModel(
            name='InventoryReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Кількість')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Коментар')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_receipt_items', to='crm.product', verbose_name='Матеріал')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.inventoryreceipt', verbose_name='Накладна')),
            ],
            options={
                'verbose_name': 'Позиція накладної',
                'verbose_name_plural': 'Позиції накладної',
                'ordering': ['receipt_id', 'id'],
                'constraints': [models.UniqueConstraint(fields=('receipt', 'product'), name='crm_unique_inventory_receipt_item_product')],
            },
        ),
    ]
