# Generated by Django 5.2.8 on 2026-03-14 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_profiles_for_existing_users(apps, schema_editor):
    user_model = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    user_profile = apps.get_model("core", "UserProfile")
    for user in user_model.objects.all():
        user_profile.objects.get_or_create(
            user=user,
            defaults={"telegram_link_code": f"LEGACY{user.pk:06d}"},
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Full name')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('sales_manager', 'Sales manager'), ('production', 'Production / Technologist'), ('executive', 'Executive')], default='sales_manager', max_length=32, verbose_name='Role')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=64, verbose_name='Telegram ID')),
                ('telegram_link_code', models.CharField(blank=True, max_length=24, unique=True, verbose_name='Telegram link code')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
                'ordering': ('full_name', 'user__email', 'user__username'),
            },
        ),
        migrations.RunPython(create_profiles_for_existing_users, migrations.RunPython.noop),
    ]
