# Generated by Django 5.2.8 on 2026-03-21 06:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_role_access'),
        ('crm', '0007_order_priority'),
        ('manufacture', '0004_productionslot_dispatcher_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram update ID')),
                ('chat_id', models.CharField(blank=True, max_length=64, verbose_name='Telegram chat ID')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Telegram username')),
                ('update_type', models.CharField(blank=True, max_length=32, verbose_name='Update type')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], db_index=True, default='processed', max_length=16, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Error message')),
                ('processed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Processed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Telegram update log',
                'verbose_name_plural': 'Telegram update logs',
                'ordering': ('-processed_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_linked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Telegram linked at'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='Telegram notifications enabled'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_notify_deadlines',
            field=models.BooleanField(default=True, verbose_name='Notify about approaching deadlines'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_notify_new_tasks',
            field=models.BooleanField(default=True, verbose_name='Notify about new tasks'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_notify_order_updates',
            field=models.BooleanField(default=True, verbose_name='Notify about order updates'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_notify_overdue',
            field=models.BooleanField(default=True, verbose_name='Notify about overdue items'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_notify_production_events',
            field=models.BooleanField(default=True, verbose_name='Notify about production events'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Telegram username'),
        ),
        migrations.CreateModel(
            name='TelegramNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_created', 'Task created'), ('task_deadline', 'Task deadline'), ('task_overdue', 'Task overdue'), ('order_status', 'Order status changed'), ('order_deadline', 'Order deadline'), ('order_overdue', 'Order overdue'), ('production_event', 'Production event')], db_index=True, max_length=32, verbose_name='Notification type')),
                ('dedupe_key', models.CharField(max_length=255, unique=True, verbose_name='Dedupe key')),
                ('message_text', models.TextField(verbose_name='Message text')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('skipped', 'Skipped'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16, verbose_name='Status')),
                ('scheduled_for', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Scheduled for')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent at')),
                ('delivery_attempts', models.PositiveIntegerField(default=0, verbose_name='Delivery attempts')),
                ('error_message', models.TextField(blank=True, verbose_name='Error message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_notifications', to='crm.order', verbose_name='Order')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_notifications', to='core.userprofile', verbose_name='Profile')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_notifications', to='manufacture.productionstage', verbose_name='Production stage')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_notifications', to='crm.task', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Telegram notification',
                'verbose_name_plural': 'Telegram notifications',
                'ordering': ('scheduled_for', 'id'),
            },
        ),
    ]
