# Generated by Django 5.2.8 on 2026-03-22 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_telegramupdatelog_userprofile_telegram_linked_at_and_more'),
        ('crm', '0007_order_priority'),
        ('manufacture', '0004_productionslot_dispatcher_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('order', 'Order'), ('task', 'Task'), ('production_stage', 'Production stage'), ('production_slot', 'Production slot')], db_index=True, max_length=32, verbose_name='Entity type')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], db_index=True, max_length=16, verbose_name='Action')),
                ('object_id', models.PositiveBigIntegerField(db_index=True, verbose_name='Object ID')),
                ('object_label', models.CharField(blank=True, max_length=255, verbose_name='Object label')),
                ('changed_fields', models.JSONField(blank=True, default=list, verbose_name='Changed fields')),
                ('snapshot_before', models.JSONField(blank=True, default=dict, verbose_name='Before')),
                ('snapshot_after', models.JSONField(blank=True, default=dict, verbose_name='After')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_audit_logs', to='crm.order', verbose_name='Order')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_audit_logs', to='manufacture.productionslot', verbose_name='Production slot')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_audit_logs', to='manufacture.productionstage', verbose_name='Production stage')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_audit_logs', to='crm.task', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Change audit log',
                'verbose_name_plural': 'Change audit logs',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
