# Generated by Django 5.2.8 on 2026-03-22 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_changeauditlog'),
        ('crm', '0007_order_priority'),
        ('manufacture', '0004_productionslot_dispatcher_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeauditlog',
            name='changed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Changed by'),
        ),
        migrations.AlterField(
            model_name='changeauditlog',
            name='order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_audit_logs', to='crm.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='changeauditlog',
            name='slot',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_audit_logs', to='manufacture.productionslot', verbose_name='Production slot'),
        ),
        migrations.AlterField(
            model_name='changeauditlog',
            name='stage',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_audit_logs', to='manufacture.productionstage', verbose_name='Production stage'),
        ),
        migrations.AlterField(
            model_name='changeauditlog',
            name='task',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_audit_logs', to='crm.task', verbose_name='Task'),
        ),
    ]
