# Generated by Django 5.2.8 on 2026-03-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_changeauditlog_changed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_notify_comments',
            field=models.BooleanField(default=True, verbose_name='Notify about comments'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_notify_new_orders',
            field=models.BooleanField(default=True, verbose_name='Notify about new orders'),
        ),
        migrations.AlterField(
            model_name='telegramnotification',
            name='notification_type',
            field=models.CharField(choices=[('task_created', 'Task created'), ('task_comment', 'Task comment'), ('order_created', 'Order created'), ('order_comment', 'Order comment'), ('task_deadline', 'Task deadline'), ('task_overdue', 'Task overdue'), ('order_status', 'Order status changed'), ('order_deadline', 'Order deadline'), ('order_overdue', 'Order overdue'), ('production_event', 'Production event')], db_index=True, max_length=32, verbose_name='Notification type'),
        ),
    ]
