# Generated by Django 5.2.8 on 2026-03-22 12:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_telegram_notify_comments_and_more'),
        ('crm', '0010_alter_client_email_alter_contact_email'),
        ('manufacture', '0005_alter_productionslot_planning_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changeauditlog',
            options={'ordering': ('-created_at', '-id'), 'verbose_name': 'Журнал змін', 'verbose_name_plural': 'Журнал змін'},
        ),
        migrations.AlterModelOptions(
            name='telegramnotification',
            options={'ordering': ('scheduled_for', 'id'), 'verbose_name': 'Telegram-сповіщення', 'verbose_name_plural': 'Telegram-сповіщення'},
        ),
        migrations.AlterModelOptions(
            name='telegramupdatelog',
            options={'ordering': ('-processed_at', '-id'), 'verbose_name': 'Журнал оновлень Telegram', 'verbose_name_plural': 'Журнал оновлень Telegram'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('full_name', 'user__email', 'user__username'), 'verbose_name': 'Профіль користувача', 'verbose_name_plural': 'Профілі користувачів'},
        ),
        migrations.AlterField(
            model_name='changeauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Створено'), ('updated', 'Оновлено'), ('deleted', 'Видалено')], db_index=True, max_length=16, verbose_name='Дія'),
        ),
        migrations.AlterField(
            model_name='changeauditlog',
            name='changed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Хто змінив'),
        ),
        migrations.AlterField(
            model_name='changeauditlog',
            name='changed_fields',
            field=models.JSONField(blank=True, default=list, verbose_name='Змінені поля'),
        ),
        migrations.AlterField(
            model_name='changeauditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='changeauditlog',
            name='entity_type',
            field=models.CharField(choices=[('order', 'Замовлення'), ('task', 'Задача'), ('production_stage', 'Виробничий етап'), ('production_slot', 'Виробничий слот')], db_index=True, max_length=32, verbose_name='Тип сутності'),
        ),
        migrations.AlterField(
            model_name='changeauditlog',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Примітка'),
        ),
        migrations.AlterField(
            model_name='changeauditlog',
            name='object_id',
            field=models.PositiveBigIntegerField(db_index=True, verbose_name='ID об’єкта'),
        ),
        migrations.AlterField(
            model_name='changeauditlog',
            name='object_label',
            field=models.CharField(blank=True, max_length=255, verbose_name='Назва об’єкта'),
        ),
        migrations.AlterField(
            model_name='changeauditlog',
            name='order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_audit_logs', to='crm.order', verbose_name='Замовлення'),
        ),
        migrations.AlterField(
            model_name='changeauditlog',
            name='slot',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_audit_logs', to='manufacture.productionslot', verbose_name='Виробничий слот'),
        ),
        migrations.AlterField(
            model_name='changeauditlog',
            name='snapshot_after',
            field=models.JSONField(blank=True, default=dict, verbose_name='Стало'),
        ),
        migrations.AlterField(
            model_name='changeauditlog',
            name='snapshot_before',
            field=models.JSONField(blank=True, default=dict, verbose_name='Було'),
        ),
        migrations.AlterField(
            model_name='changeauditlog',
            name='stage',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_audit_logs', to='manufacture.productionstage', verbose_name='Виробничий етап'),
        ),
        migrations.AlterField(
            model_name='changeauditlog',
            name='task',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_audit_logs', to='crm.task', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='telegramnotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='telegramnotification',
            name='dedupe_key',
            field=models.CharField(max_length=255, unique=True, verbose_name='Ключ дедуплікації'),
        ),
        migrations.AlterField(
            model_name='telegramnotification',
            name='delivery_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Спроб доставки'),
        ),
        migrations.AlterField(
            model_name='telegramnotification',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Текст помилки'),
        ),
        migrations.AlterField(
            model_name='telegramnotification',
            name='message_text',
            field=models.TextField(verbose_name='Текст повідомлення'),
        ),
        migrations.AlterField(
            model_name='telegramnotification',
            name='notification_type',
            field=models.CharField(choices=[('task_created', 'Створено задачу'), ('task_comment', 'Коментар до задачі'), ('order_created', 'Створено замовлення'), ('order_comment', 'Коментар до замовлення'), ('task_deadline', 'Дедлайн задачі'), ('task_overdue', 'Прострочена задача'), ('order_status', 'Змінено статус замовлення'), ('order_deadline', 'Дедлайн замовлення'), ('order_overdue', 'Прострочене замовлення'), ('production_event', 'Подія виробництва')], db_index=True, max_length=32, verbose_name='Тип сповіщення'),
        ),
        migrations.AlterField(
            model_name='telegramnotification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_notifications', to='crm.order', verbose_name='Замовлення'),
        ),
        migrations.AlterField(
            model_name='telegramnotification',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Вміст'),
        ),
        migrations.AlterField(
            model_name='telegramnotification',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_notifications', to='core.userprofile', verbose_name='Профіль'),
        ),
        migrations.AlterField(
            model_name='telegramnotification',
            name='scheduled_for',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Заплановано на'),
        ),
        migrations.AlterField(
            model_name='telegramnotification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Надіслано'),
        ),
        migrations.AlterField(
            model_name='telegramnotification',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_notifications', to='manufacture.productionstage', verbose_name='Виробничий етап'),
        ),
        migrations.AlterField(
            model_name='telegramnotification',
            name='status',
            field=models.CharField(choices=[('pending', 'У черзі'), ('sent', 'Надіслано'), ('skipped', 'Пропущено'), ('failed', 'Помилка')], db_index=True, default='pending', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='telegramnotification',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_notifications', to='crm.task', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='telegramupdatelog',
            name='chat_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='ID Telegram-чату'),
        ),
        migrations.AlterField(
            model_name='telegramupdatelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='telegramupdatelog',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Текст помилки'),
        ),
        migrations.AlterField(
            model_name='telegramupdatelog',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Вміст'),
        ),
        migrations.AlterField(
            model_name='telegramupdatelog',
            name='processed_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Оброблено'),
        ),
        migrations.AlterField(
            model_name='telegramupdatelog',
            name='status',
            field=models.CharField(choices=[('processed', 'Оброблено'), ('ignored', 'Проігноровано'), ('failed', 'Помилка')], db_index=True, default='processed', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='telegramupdatelog',
            name='update_id',
            field=models.BigIntegerField(db_index=True, unique=True, verbose_name='ID оновлення Telegram'),
        ),
        migrations.AlterField(
            model_name='telegramupdatelog',
            name='update_type',
            field=models.CharField(blank=True, max_length=32, verbose_name='Тип оновлення'),
        ),
        migrations.AlterField(
            model_name='telegramupdatelog',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ім’я користувача Telegram'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ПІБ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Адміністратор'), ('sales_manager', 'Менеджер з продажу'), ('production', 'Виробництво / технолог'), ('executive', 'Керівник')], default='sales_manager', max_length=32, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='ID Telegram-чату'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_link_code',
            field=models.CharField(blank=True, max_length=24, unique=True, verbose_name='Код прив’язки Telegram'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_linked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Прив’язано до Telegram'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='Telegram-сповіщення увімкнено'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_notify_comments',
            field=models.BooleanField(default=True, verbose_name='Сповіщати про коментарі'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_notify_deadlines',
            field=models.BooleanField(default=True, verbose_name='Сповіщати про наближення дедлайнів'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_notify_new_orders',
            field=models.BooleanField(default=True, verbose_name='Сповіщати про нові замовлення'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_notify_new_tasks',
            field=models.BooleanField(default=True, verbose_name='Сповіщати про нові задачі'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_notify_order_updates',
            field=models.BooleanField(default=True, verbose_name='Сповіщати про оновлення замовлень'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_notify_overdue',
            field=models.BooleanField(default=True, verbose_name='Сповіщати про прострочення'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_notify_production_events',
            field=models.BooleanField(default=True, verbose_name='Сповіщати про події виробництва'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ім’я користувача Telegram'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
    ]
