# Generated by Django 5.2.8 on 2025-12-25 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва верстата')),
                ('type', models.CharField(choices=[('laser', 'Лазер'), ('bending', 'Гибка'), ('welding', 'Сварка'), ('painting', 'Покраска'), ('other', 'Інше')], db_index=True, default='other', max_length=20, verbose_name='Тип верстата')),
                ('workday_start', models.TimeField(blank=True, help_text='Якщо порожньо — використовується загальний графік', null=True, verbose_name='Початок робочого дня')),
                ('workday_end', models.TimeField(blank=True, help_text='Якщо порожньо — використовується загальний графік', null=True, verbose_name='Кінець робочого дня')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
            ],
            options={
                'verbose_name': 'Верстат',
                'verbose_name_plural': 'Верстати',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва дільниці')),
                ('type', models.CharField(choices=[('welding_section', 'Зварювальна дільниця'), ('painting_section', 'Фарбувальна дільниця'), ('assembly_section', 'Збірочна дільниця'), ('storage', 'Склад / зберігання'), ('other', 'Інше')], db_index=True, default='other', max_length=32, verbose_name='Тип дільниці')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
            ],
            options={
                'verbose_name': 'Виробнича дільниця',
                'verbose_name_plural': 'Виробничі дільниці',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Початок')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Кінець')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Коментар')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='manufacture.machine', verbose_name='Верстат')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='crm.order', verbose_name='Замовлення')),
                ('work_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='manufacture.workunit', verbose_name='Виробнича дільниця')),
            ],
            options={
                'verbose_name': 'Слот виробництва',
                'verbose_name_plural': 'Слоти виробництва',
                'ordering': ['start_datetime', 'id'],
            },
        ),
    ]
