# Generated by Django 5.2.8 on 2026-03-15 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def _infer_stage_type(slot):
    machine = getattr(slot, "machine", None)
    work_unit = getattr(slot, "work_unit", None)
    if machine and machine.type == "painting":
        return "painting"
    if work_unit and work_unit.type == "painting_section":
        return "painting"
    if work_unit and work_unit.type == "storage":
        return "ready_to_ship"
    return "execution"


def _infer_stage_status(slot, now):
    if slot.end_datetime and slot.end_datetime < now:
        return "done"
    if slot.start_datetime and slot.start_datetime <= now and (
        not slot.end_datetime or slot.end_datetime >= now
    ):
        return "in_progress"
    if slot.start_datetime and slot.start_datetime > now:
        return "scheduled"
    return "new"


def backfill_production_stages(apps, schema_editor):
    OrderItem = apps.get_model("crm", "OrderItem")
    ProductionSlot = apps.get_model("manufacture", "ProductionSlot")
    ProductionStage = apps.get_model("manufacture", "ProductionStage")
    now = timezone.now()

    for slot in ProductionSlot.objects.select_related("machine", "work_unit").all():
        order_item = OrderItem.objects.filter(order_id=slot.order_id).order_by("id").first()
        if not order_item:
            continue

        stage_status = _infer_stage_status(slot, now)
        stage = ProductionStage.objects.create(
            order_item_id=order_item.id,
            stage_type=_infer_stage_type(slot),
            status=stage_status,
            sequence=1,
            planned_start=slot.start_datetime,
            planned_end=slot.end_datetime,
            started_at=slot.start_datetime if stage_status in {"in_progress", "done"} else None,
            completed_at=slot.end_datetime if stage_status == "done" else None,
            comment=slot.comment or "",
        )
        slot.stage_id = stage.id
        slot.save(update_fields=["stage"])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_order_manager'),
        ('manufacture', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='type',
            field=models.CharField(choices=[('laser', 'Лазер'), ('bending', 'Гибка'), ('welding', 'Зварка'), ('painting', 'Фарбування'), ('other', 'Інше')], db_index=True, default='other', max_length=20, verbose_name='Тип верстата'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='workday_end',
            field=models.TimeField(blank=True, help_text='Якщо порожньо, використовується загальний графік.', null=True, verbose_name='Кінець робочого дня'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='workday_start',
            field=models.TimeField(blank=True, help_text='Якщо порожньо, використовується загальний графік.', null=True, verbose_name='Початок робочого дня'),
        ),
        migrations.CreateModel(
            name='ProductionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(choices=[('intake', 'Приймання'), ('procurement', 'Закупка матеріалів'), ('execution', 'Виконання'), ('painting', 'Фарбування'), ('ready_to_ship', 'Готово до відправки')], db_index=True, default='execution', max_length=32, verbose_name='Тип етапу')),
                ('status', models.CharField(choices=[('new', 'Новий'), ('scheduled', 'Заплановано'), ('in_progress', 'В роботі'), ('blocked', 'Заблоковано'), ('done', 'Завершено')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('sequence', models.PositiveIntegerField(db_index=True, default=1, verbose_name='Порядок')),
                ('planned_start', models.DateTimeField(blank=True, null=True, verbose_name='Плановий початок')),
                ('planned_end', models.DateTimeField(blank=True, null=True, verbose_name='Планове завершення')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Фактичний старт')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Фактичне завершення')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_stages', to='crm.orderitem', verbose_name='Позиція замовлення')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_stages', to=settings.AUTH_USER_MODEL, verbose_name='Відповідальний')),
            ],
            options={
                'verbose_name': 'Виробничий етап',
                'verbose_name_plural': 'Виробничі етапи',
                'ordering': ['order_item__order_id', 'sequence', 'id'],
            },
        ),
        migrations.AddField(
            model_name='productionslot',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='manufacture.productionstage', verbose_name='Етап'),
        ),
        migrations.RunPython(backfill_production_stages, migrations.RunPython.noop),
    ]
