# Generated by Django 5.2.8 on 2026-03-20 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_order_priority'),
        ('manufacture', '0002_alter_machine_type_alter_machine_workday_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='available_weekdays',
            field=models.CharField(default='0,1,2,3,4', help_text='Номери днів тижня через кому: 0=пн, 1=вт ... 6=нд.', max_length=32, verbose_name='Дні доступності'),
        ),
        migrations.AddField(
            model_name='machine',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AddField(
            model_name='productionslot',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Зафіксований слот не буде пересунуто автопланувальником.', verbose_name='Зафіксовано вручну'),
        ),
        migrations.AddField(
            model_name='productionslot',
            name='planning_mode',
            field=models.CharField(choices=[('auto', 'Авто'), ('manual', 'Ручний')], db_index=True, default='auto', max_length=12, verbose_name='Режим планування'),
        ),
        migrations.AddField(
            model_name='workunit',
            name='available_weekdays',
            field=models.CharField(default='0,1,2,3,4', help_text='Номери днів тижня через кому: 0=пн, 1=вт ... 6=нд.', max_length=32, verbose_name='Дні доступності'),
        ),
        migrations.AddField(
            model_name='workunit',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AddField(
            model_name='workunit',
            name='workday_end',
            field=models.TimeField(blank=True, help_text='Якщо порожньо, використовується 17:00.', null=True, verbose_name='Кінець робочого дня'),
        ),
        migrations.AddField(
            model_name='workunit',
            name='workday_start',
            field=models.TimeField(blank=True, help_text='Якщо порожньо, використовується 08:00.', null=True, verbose_name='Початок робочого дня'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='workday_end',
            field=models.TimeField(blank=True, help_text='Якщо порожньо, використовується 17:00.', null=True, verbose_name='Кінець робочого дня'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='workday_start',
            field=models.TimeField(blank=True, help_text='Якщо порожньо, використовується 08:00.', null=True, verbose_name='Початок робочого дня'),
        ),
        migrations.CreateModel(
            name='ProductionSlotChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_reference', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID слота')),
                ('action', models.CharField(choices=[('created', 'Створено'), ('updated', 'Оновлено'), ('deleted', 'Видалено')], db_index=True, max_length=16, verbose_name='Дія')),
                ('source', models.CharField(choices=[('auto', 'Автопланувальник'), ('manual', 'Ручне редагування'), ('system', 'Система')], default='system', max_length=16, verbose_name='Джерело')),
                ('snapshot_before', models.JSONField(blank=True, default=dict, verbose_name='Було')),
                ('snapshot_after', models.JSONField(blank=True, default=dict, verbose_name='Стало')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примітка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_slot_change_logs', to=settings.AUTH_USER_MODEL, verbose_name='Ким змінено')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_change_logs', to='crm.order', verbose_name='Замовлення')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='manufacture.productionslot', verbose_name='Слот')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_change_logs', to='manufacture.productionstage', verbose_name='Етап')),
            ],
            options={
                'verbose_name': 'Історія зміни слота',
                'verbose_name_plural': 'Історія змін слотів',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ResourceDowntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Початок')),
                ('end_datetime', models.DateTimeField(verbose_name='Кінець')),
                ('downtime_type', models.CharField(choices=[('maintenance', 'Технічне обслуговування'), ('manual_block', 'Ручне блокування'), ('downtime', 'Простій'), ('holiday', 'Неробочий інтервал')], db_index=True, default='downtime', max_length=20, verbose_name='Тип простою')),
                ('is_blocking', models.BooleanField(default=True, verbose_name='Блокує планування')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Коментар')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downtimes', to='manufacture.machine', verbose_name='Верстат')),
                ('work_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downtimes', to='manufacture.workunit', verbose_name='Виробнича дільниця')),
            ],
            options={
                'verbose_name': 'Простій ресурсу',
                'verbose_name_plural': 'Простої ресурсів',
                'ordering': ['start_datetime', 'id'],
            },
        ),
    ]
