# Generated by Django 5.2.8 on 2026-03-21 05:31

from django.db import migrations, models


def backfill_slot_metadata(apps, schema_editor):
    ProductionSlot = apps.get_model("manufacture", "ProductionSlot")

    for slot in ProductionSlot.objects.select_related(
        "stage",
        "stage__order_item",
        "stage__order_item__product",
    ):
        changed = []
        if slot.stage_id and slot.operation_type == "other":
            slot.operation_type = slot.stage.stage_type
            changed.append("operation_type")
        if not slot.purpose and slot.stage_id:
            slot.purpose = f"{slot.stage.order_item.product.name} / {slot.stage.get_stage_type_display()}"
            changed.append("purpose")
        if slot.planning_source == "system":
            if slot.planning_mode == "auto":
                slot.planning_source = "planner"
            elif slot.planning_mode == "manual" or slot.is_locked:
                slot.planning_source = "dispatcher"
            changed.append("planning_source")
        if changed:
            slot.save(update_fields=changed)


class Migration(migrations.Migration):

    dependencies = [
        ("manufacture", "0003_machine_available_weekdays_machine_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionslot",
            name="dispatcher_comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Коментар диспетчера"),
        ),
        migrations.AddField(
            model_name="productionslot",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("intake", "Приймання"),
                    ("procurement", "Закупка матеріалів"),
                    ("execution", "Виконання"),
                    ("painting", "Фарбування"),
                    ("ready_to_ship", "Готово до відправки"),
                    ("other", "Інша операція"),
                ],
                db_index=True,
                default="other",
                max_length=32,
                verbose_name="Тип операції",
            ),
        ),
        migrations.AddField(
            model_name="productionslot",
            name="planning_source",
            field=models.CharField(
                choices=[
                    ("planner", "Автопланувальник"),
                    ("dispatcher", "Диспетчер"),
                    ("admin", "Admin"),
                    ("system", "Система"),
                    ("seed", "Demo seed"),
                ],
                db_index=True,
                default="system",
                max_length=16,
                verbose_name="Джерело планування",
            ),
        ),
        migrations.AddField(
            model_name="productionslot",
            name="purpose",
            field=models.CharField(blank=True, max_length=255, verbose_name="Призначення"),
        ),
        migrations.AddField(
            model_name="productionslot",
            name="slot_type",
            field=models.CharField(
                choices=[
                    ("work", "Робочий слот"),
                    ("setup", "Налаштування"),
                    ("transfer", "Переміщення"),
                    ("buffer", "Буфер / очікування"),
                    ("reservation", "Резерв"),
                    ("other", "Інше"),
                ],
                db_index=True,
                default="work",
                max_length=20,
                verbose_name="Тип слота",
            ),
        ),
        migrations.AlterField(
            model_name="productionslot",
            name="comment",
            field=models.CharField(blank=True, max_length=500, verbose_name="Службовий коментар"),
        ),
        migrations.AlterField(
            model_name="productionstage",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новий"),
                    ("scheduled", "Заплановано"),
                    ("in_progress", "В роботі"),
                    ("blocked", "Заблоковано"),
                    ("cancelled", "Скасовано"),
                    ("done", "Завершено"),
                ],
                db_index=True,
                default="new",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.RunPython(backfill_slot_metadata, migrations.RunPython.noop),
    ]
