# Generated by Django 5.2.8 on 2026-03-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0004_productionslot_dispatcher_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionslot',
            name='planning_source',
            field=models.CharField(choices=[('planner', 'Автопланувальник'), ('dispatcher', 'Диспетчер'), ('admin', 'Адміністратор'), ('system', 'Система'), ('seed', 'Демо-наповнення')], db_index=True, default='system', max_length=16, verbose_name='Джерело планування'),
        ),
    ]
